### ISSUE TITLE
Crasha e não aceita nenhuma matrícula

### ISSUE THREAD

**Issue by DUDUKorte** [GabrielCM16/MeuIF_apk#1]
independente da matrícula que coloca, mesmo sendo uma real, ele não aceita, da "erro ao procurar matrícula" e se não colocar nada e apertar continuar o app crasha

**Comment by GabrielCM16** [comment]
Thanks pelo feedback, a parte de crasha sem nada no campo eu preciso
verificar pq nem tinha visto, mas a parte de não encontrar número de
matrícula está certo, no banco de dados tenho poucos números de matrículas
cadastrados, pq eu ea helo n pegamos os dados da sepae ainda, e por ventura
quando isso acontecer a gente n vai poder estar fazendo o app, ent no bd só
tem dados nossos e de quem eu pedi tipo tem o do Pedro miotto, pq a gente é
lider de sala ent tem uma visão diferente do app, se vc quiser testar dps
me passa seu numero de matrícula pra mim criar no banco de dados, tipo só
pra testes pq a gente n pode fazer isso por isso n tem o número de todo
mundo

Em sáb, 22 de jul de 2023 23:26, esquilo korte ***@***.***>
escreveu:
